### ISSUE TITLE
Build binary classifier using MI as training data and real as testing with biologically relevant channels and frequency filters

### ISSUE THREAD

**Issue by ghost** [vsarin92/EEG_DL_Dissertation#6]

**Comment by vsarin92** [comment]
Closed with commit https://github.com/vsarin92/EEG_DL_Dissertation/commit/5fcf298d2d874dfd6902704035cd4da361808b49

**Comment by ghost** [comment]
Closed with commit https://github.com/vsarin92/EEG_DL_Dissertation/commit/5fcf298d2d874dfd6902704035cd4da361808b49
